use std::{env,fs,path::{Path,PathBuf},process::Command};
use walkdir::WalkDir;

fn has_command(name:&str)->bool{env::var_os("PATH").and_then(|paths|env::split_paths(&paths).find_map(|p|{let f=p.join(if cfg!(windows){format!("{name}.exe")}else{name.into()});f.is_file().then_some(f)})).is_some()}
#[tauri::command] fn chdman_status()->bool{has_command("chdman")||Path::new(if cfg!(windows){"chdman.exe"}else{"chdman"}).is_file()}
fn extensions(mode:&str)->&'static[&'static str]{if mode=="convert"{&["cue","gdi","toc","iso","img","raw"]}else{&["chd"]}}
#[tauri::command] fn scan_files(folder:String,mode:String,recursive:bool)->Result<Vec<String>,String>{let depth=if recursive{usize::MAX}else{1};let mut v:Vec<_>=WalkDir::new(&folder).max_depth(depth).into_iter().filter_map(Result::ok).filter(|e|e.file_type().is_file()).filter(|e|e.path().extension().and_then(|x|x.to_str()).is_some_and(|x|extensions(&mode).contains(&x.to_ascii_lowercase().as_str()))).map(|e|e.path().display().to_string()).collect();v.sort();Ok(v)}
fn unique_path(path:PathBuf)->PathBuf{if !path.exists(){return path}let dir=path.parent().unwrap_or(Path::new(""));let stem=path.file_stem().unwrap_or_default().to_string_lossy();let ext=path.extension().map(|x|format!(".{}",x.to_string_lossy())).unwrap_or_default();for n in 1..{let p=dir.join(format!("{stem} ({n}){ext}"));if !p.exists(){return p}}unreachable!()}
fn command_for(path:&Path,mode:&str)->(&'static str,&'static str){if mode=="verify"{return("verify","")}if mode=="extract"{return("extractcd","cue")}match path.extension().and_then(|x|x.to_str()).unwrap_or("").to_ascii_lowercase().as_str(){"cue"|"gdi"|"toc"=>("createcd","chd"),"iso"=>("createdvd","chd"),"raw"=>("createraw","chd"),_=>("createhd","chd")}}
#[tauri::command] fn process_batch(source:String,output:String,mode:String,recursive:bool,delete_source:bool)->Result<Vec<String>,String>{if !chdman_status(){return Err("chdman was not found. Install MAME first.".into())}let files=scan_files(source.clone(),mode.clone(),recursive)?;let mut logs=Vec::new();for item in files{let input=PathBuf::from(&item);let(cmd,ext)=command_for(&input,&mode);let mut c=Command::new("chdman");c.arg(cmd).arg("-i").arg(&input);let out=if mode=="verify"{None}else{let rel=input.strip_prefix(&source).unwrap_or(&input);let target=Path::new(&output).join(rel).with_extension(ext);if let Some(p)=target.parent(){fs::create_dir_all(p).map_err(|e|e.to_string())?}let u=unique_path(target);c.arg("-o").arg(&u);Some(u)};let result=c.output().map_err(|e|e.to_string())?;if result.status.success(){logs.push(format!("OK: {}",input.display()));if delete_source{fs::remove_file(&input).map_err(|e|e.to_string())?}}else{logs.push(format!("FAILED: {} — {}",input.display(),String::from_utf8_lossy(&result.stderr)))}if let Some(p)=out{if !result.status.success(){let _=fs::remove_file(p);}}}Ok(logs)}
fn main(){tauri::Builder::default().plugin(tauri_plugin_dialog::init()).invoke_handler(tauri::generate_handler![chdman_status,scan_files,process_batch]).run(tauri::generate_context!()).expect("failed to run application")}
