import './style.css';
import { invoke } from '@tauri-apps/api/core';
import { open } from '@tauri-apps/plugin-dialog';

const app=document.querySelector('#app');
app.innerHTML=`<header><div><h1>Batch Convert to CHD <b>Next</b></h1><p>Windows · macOS · Linux</p></div><span id="dep">Checking CHDMAN…</span></header><main><section class="panel"><nav><button class="tab active" data-mode="convert">Convert</button><button class="tab" data-mode="verify">Verify</button><button class="tab" data-mode="extract">Extract</button></nav><label>Source folder</label><div class="field"><input id="source" readonly><button id="pick-source">Browse</button></div><div id="output-row"><label>Output folder</label><div class="field"><input id="output" readonly><button id="pick-output">Browse</button></div></div><div class="options"><label><input type="checkbox" id="recursive" checked> Include subfolders</label><label><input type="checkbox" id="delete"> Delete source after success</label></div><div class="summary"><strong id="count">0</strong><span>compatible files</span></div><button class="primary" id="start">Start conversion</button></section><section class="console"><div class="console-title">Activity log <button id="clear">Clear</button></div><pre id="log">Ready.</pre></section></main>`;
let mode='convert';
const $=s=>document.querySelector(s), log=m=>{$('#log').textContent+=`\n${m}`;$('#log').scrollTop=$('#log').scrollHeight};
async function pick(id){const p=await open({directory:true,multiple:false});if(p){$(id).value=p;if(id==='#source'&&!$('#output').value)$('#output').value=p;await scan();}}
async function scan(){if(!$('#source').value)return;try{const files=await invoke('scan_files',{folder:$('#source').value,mode,recursive:$('#recursive').checked});$('#count').textContent=files.length;}catch(e){log(`ERROR: ${e}`)}}
$('#pick-source').onclick=()=>pick('#source'); $('#pick-output').onclick=()=>pick('#output'); $('#recursive').onchange=scan; $('#clear').onclick=()=>$('#log').textContent='';
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;$('#output-row').hidden=mode==='verify';$('#start').textContent=mode==='convert'?'Start conversion':mode==='extract'?'Start extraction':'Start verification';scan();});
$('#start').onclick=async()=>{const source=$('#source').value,output=$('#output').value||source;if(!source)return log('Select a source folder.');$('#start').disabled=true;try{const lines=await invoke('process_batch',{source,output,mode,recursive:$('#recursive').checked,deleteSource:$('#delete').checked});lines.forEach(log);await scan();}catch(e){log(`ERROR: ${e}`)}finally{$('#start').disabled=false}};
invoke('dependency_status').then(x=>{$('#dep').textContent=`CHDMAN ${x.chdman?'✓':'✕'} · 7-Zip ${x.seven_zip?'✓':'–'} · MaxCSO ${x.maxcso?'✓':'–'}`;$('#dep').className=x.chdman?'ok':'bad'});
